services:
  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vulnerability_scanner
    ports:
      - "5432:5432"
    networks:
      - scanner_network

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server
    networks:
      - scanner_network

  scanner:
    build: .
    command: ["waitress-serve", "--host=0.0.0.0", "--port=5000", "server:app"]
    #command: ["flask", "run", "--host=0.0.0.0", "--port=5000"]
    restart: always
    ports:
      - "5000:5000"
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
    volumes:
      - ./vulnerabilities:/app/vulnerabilities
    networks:
      - scanner_network
      - default  # Permet l'accès au réseau par défaut de Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Permet l'accès à l'hôte

  worker:
    build: .
    command: ["rq", "worker", "scan_tasks", "--with-scheduler"]
    depends_on:
      - db
      - redis
    env_file:
      - .env
    volumes:
      - ./vulnerabilities:/app/vulnerabilities
    networks:
      - scanner_network
      - default  # Permet l'accès au réseau par défaut de Docker
    extra_hosts:
      - "host.docker.internal:host-gateway"  # Permet l'accès à l'hôte

networks:
  scanner_network:
    external: true  # Utilise le réseau existant