services:

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vulnerability_scanner
    ports:
      - "5432:5432"

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - "6379:6379"
    command: redis-server

  scanner:
    build: .
    #command: ["waitress-serve", "--host=0.0.0.0", "--port=5000", "server:app"] # for production
    command: ["python", "server.py"] # for development
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app

  worker:
    build: .
    command: ["rq", "worker", "scan_tasks", "--with-scheduler"]
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

