version: '3.8'

services:

  scanner:
    build: .
    restart: always
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - .env

  worker:
    build: .
    command: rq worker
    volumes:
      - .:/app
    depends_on:
      - redis
      - db
    env_file:
      - .env

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vulnerability_scanner
    ports:
      - "5432:5432"
    #volumes:
    #  - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7.4-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --save 60 1 --loglevel warning

volumes:
  postgres_data:
